spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/songs_lib_author_dev
    username: adminauthor
    password: AdminAuthor
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

  flyway:
    default-schema: public
    #enabled: true
    #baseline-on-migrate: true
config:
  defaultPage: 0
  defaultSize: 10
server:
  port: 8086