spring:
  data.redis.database: 0
  data.redis.host: localhost
  data.redis.port: 6379
  data.redis.password: mypass
  data.redis.timeout: 60000
  data.redis.client-type: lettuce
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/alexlakers-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
token:
  resource-id: songs-lib
  principal-attribute: preferred_username
logging:
  level:
    org.sprigframework.data.redis: DEBUG