services:
  database:
    image: postgres:17
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: adminauthor
      POSTGRES_PASSWORD: AdminAuthor
      POSTGRES_DB: songs_lib_author_dev
    volumes:
      - db-data:/var/lib/postgres/data
    networks:
      backend-net:
        aliases:
          - database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  databasetwo:
    image: postgres:17
    ports:
      - 5452:5432
    environment:
      POSTGRES_USER: adminsong
      POSTGRES_PASSWORD: AdminSong
      POSTGRES_DB: songs_lib_song_dev
    volumes:
      - db-data-two:/var/lib/postgres/data
    networks:
      backend-net:
        aliases:
          - databasetwo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  configserver:
    image: songs-lib/config-server:0.0.1-SNAPSHOT
    networks:
      backend-net:
        aliases:
          - configserver
    ports:
      - 8888:8888
    environment:
      ENCRYPT_KEY: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo
  authorservice:
    image: songs-lib/author-service:0.0.1-SNAPSHOT
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/songs_lib_author_dev
    networks:
      backend-net:
        aliases:
            - authorservice
    ports:
      - 8086:8086
  eurekaserver:
    image: songs-lib/eureka-server:0.0.1-SNAPSHOT
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend-net:
        aliases:
            - eurekaserver
    ports:
      - 8081:8081
  gatewayserver:
    image: songs-lib/gateway-server:0.0.1-SNAPSHOT
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend-net:
        aliases:
            - gatewayserver
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    #restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/realm-export.json
    command:
      - start-dev
    ports:
      - 8080:8080
    networks:
      backend-net:
        aliases:
          - keycloak
  frontendclient:
    image: songs-lib/gateway-server:0.0.1-SNAPSHOT
    depends_on:
      gatewayserver:
        condition: service_started
    networks:
      backend-net:
        aliases:
          - frontend

networks:
  backend-net:
    driver: bridge
volumes:
  db-data:
  db-data-two: