global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'author-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['authorservice:8086']
              #authorservice
  - job_name: 'song-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['localhost:8090']
              #songservice