spring:
  datasource:
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5452/songs_lib_song_dev
    username: adminsong
    password: AdminSong
  jpa:
    open-in-view: false
logging:
  level:
    com.alex.web.microservices.songs.lib.songs.SongsServiceApplicationRunner: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG


server:
  port: 8090
pagination:
  default:
   page: 0
   size: 50
   column: id
   direction: ASC
