spring:
  kafka:
    bootstrap-servers: localhost:9092
        #kafkaserver
    cloud:
      loadbalancer:
        enabled: true
      function:
        definition: inputModificationSong
      stream:
        bindings:
          inputModificationSong-in-0:
            destination: songModificationTopic
            group: author-group
            content-type: application/json
#redis
  data:
    redis:
      database: 0
      host: localhost
      #redisserver
      port: 6379
      password: mypass
      timeout: 60000
      client-type: lettuce
#database
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
#FlayAway
  flyway:
    default-schema: public
    #enabled: true
    #baseline-on-migrate: true
    
config:
  defaultPage: 0
  defaultSize: 10
#eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
      #eurekaserver
      
management:
#for zipkin
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
                #zipkin
      sampling:
        probability: 1
#for actuator
  endpoints:
    web:
      exposure:
        include: "*"
#serviceUrl=service-url

#for micrometr
logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false
