spring:
  cloud:
    loadbalancer:
      enabled: true
  #routes
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: author-service
          uri: lb://author-service
          predicates:
            - Path=/authors/**
          filters:
            - RewritePath=/(?<path>.*), /api/v1/$\{path}
            - RemoveRequestHeader=Cookie,Set-Cookie
        - id: song-service
          uri: lb://song-service
          predicates:
            - Path=/songs/**
          filters:
            - RewritePath=/(?<path>.*), /api/v1/$\{path}
            - RemoveRequestHeader=Cookie,Set-Cookie
#eureka
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
      #eurekaserver
  instance:
    prefer-ip-address: true


management:
#for zipkin
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
                #zipkin
      sampling:
        probability: 1
#for actuator
  endpoints:
    web:
      exposure:
        include: "*"
#serviceUrl=service-url

#for micrometr
logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  include-application-name: false
