--liquibase formatted sql

--changeset alex:1
CREATE TABLE IF NOT EXISTS song (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
    author_id BIGINT NOT NULL ,
    name VARCHAR(128) NOT NULL ,
    album VARCHAR(128) DEFAULT 'single',
    UNIQUE (name,album),
    CONSTRAINT pk_song_id PRIMARY KEY (id)

);
--rollback DROP TABLE song;